server:
  port: 8080

spring:
  application:
    name: reservation-service
  datasource:
    username: '**USERNAME**'
    url: jdbc:postgresql://localhost:5432/reservation-service
    password: '**PASSWORD**'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  servlet:
    multipart:
#      max-file-size: '5000KB'
#      max-request-size: '5000KB'
      enabled: true
  security:
    user:
      name: 'user'
      password: 'user'
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
banner:
  location: 'banner.txt'
reservation:
  app:
    jwtSecret: 'secret'
    jwtExpirationMs: '86400000'
    jwtRefreshExpirationMs: '86400000'
    baseUrlDeploy:
    baseUrlLocal: 'http://localhost:8080/'